import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './*.html',
        './assets/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                black: '#000000',
                slate: {
                    900: '#0B0D12',
                    800: '#14171E',
                    700: '#1A1E27',
                },
                accentsBlue: '#4DA6FF',
                darkPanel: '#07080B',
                offWhite: '#F3F4F6',
                'surface': '#f9f9f9',
                'surface-container-low': '#f3f3f3',
                'surface-container': '#eeeeee',
                'surface-container-high': '#e8e8e8',
                'surface-container-highest': '#e2e2e2',
                'surface-container-lowest': '#ffffff',
                'surface-bright': '#f9f9f9',
                'surface-dim': '#dadada',
                'surface-variant': '#e2e2e2',
                'background': '#f9f9f9',
                'on-surface': '#1a1c1c',
                'on-surface-variant': '#424655',
                'on-background': '#1a1c1c',
                'inverse-surface': '#2f3131',
                'inverse-on-surface': '#f0f1f1',
                'outline': '#727787',
                'outline-variant': '#c2c6d8',
                'primary': '#0056c6',
                'on-primary': '#ffffff',
                'primary-container': '#006df8',
                'on-primary-container': '#fefcff',
                'primary-fixed': '#d9e2ff',
                'primary-fixed-dim': '#b0c6ff',
                'on-primary-fixed': '#001945',
                'on-primary-fixed-variant': '#00429c',
                'inverse-primary': '#b0c6ff',
                'surface-tint': '#0058cb',
                'secondary': '#9e4227',
                'on-secondary': '#ffffff',
                'tertiary': '#5d5c5b',
                'on-tertiary': '#ffffff',
                'error': '#ba1a1a',
                'on-error': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
                full: '9999px',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                heading: ['Anton', 'Impact', 'sans-serif-condensed', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
                mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
            },
        },
    },
    plugins: [
        forms,
    ],
}
